#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/presentation/proposalMgmt

#
# To add new directories, create the directories and add their names
# this list. Be sure to copy a Makefile into each directory. Then add a
# "../" to the ROOT variable, and add the directory name to the end of.
# the PACKAGEDIR variable.
#

#
# To add more Java classes, create the .java files and add their names to
# this list (without the .java extension).
#
CLASSES = \
    	manageproposal \
	newproposalp1 \
	newproposalp1a \
	newproposalp2 \
	newproposalp3uc \
	newproposalp3nonuc \
	newproposalp4 \
	newproposalp4a \
	preview  \
	quickview  \
	previewa  \
	quickviewa  \
	editproposal \
	proposalp1 \
	proposalp1a \
	proposalp2 \
	proposalp3uc \
	proposalp3nonuc \
	proposalp4 \
	proposalp4a \
	showcomments \
	showrescomments \
	proposalstatus \
	proposaladminmenu \
	aproposallog \
	chproposallog \
	cacclog \
	proposallog \
	approveproposal \
	approvepmesg \
	checkroute \
	addaccounts \
	internalcomments \
	information \
	committeeinfo \
	piprofile	\
	piprofileinfo \
	pilist \
	operatorslist \
	projectlistmenu \
	ucsdprojects\
	nonucsdprojects\
	unpaidprojects \
	ucprojectinfo\
	nonucprojectinfo \
	piprojectslist	\
	newproposalmenu \
	biproposalmenu  \
	showapproveconf
	 
	
      
	
HTML_DIR = ../../resources/proposalMgmt

HTML_CLASSES = 		\
	manageproposalHTML  \
	newproposalp1HTML \
	newproposalp1aHTML \
	newproposalp2HTML \
	newproposalp3ucHTML \
	newproposalp3nonucHTML \
	newproposalp4HTML  \
	newproposalp4aHTML  \
	previewHTML    \
	quickviewHTML    \
	previewaHTML    \
	quickviewaHTML    \
	editproposalHTML  \
	proposalp1HTML \
	proposalp1aHTML \
	proposalp2HTML \
	proposalp3ucHTML \
	proposalp3nonucHTML \
	proposalp4HTML \
	proposalp4aHTML \
	showcommentsHTML \
	showrescommentsHTML \
	proposalstatusHTML\
        proposaladminmenuHTML \
	aproposallogHTML \
	chproposallogHTML \
	cacclogHTML \
	proposallogHTML\
	approveproposalHTML \
	approvepmesgHTML \
	checkrouteHTML \
	addaccountsHTML \
	internalcommentsHTML\
	informationHTML \
	committeeinfoHTML \
	newproposalScriptHTML \
	newproposalaScriptHTML \
	newproposalp2ScriptHTML \
	newproposalp3ScriptHTML \
	newproposalp4ScriptHTML \
	newproposalp4aScriptHTML \
	previewScriptHTML \
	previewaScriptHTML \
	piprofileHTML   \
	piprofileinfoHTML  \
	pilistHTML \
	operatorslistHTML  \
	projectlistmenuHTML \
	ucsdprojectsHTML\
	nonucsdprojectsHTML\
	unpaidprojectsHTML\
	ucprojectinfoHTML\
	nonucprojectinfoHTML\
	piprojectslistHTML \
	newproposalmenuHTML \
	biproposalmenuHTML \
	showapproveconfHTML


# The "?Edit.po" dummy query string is used so the URL mapping only maps this
# sepcific URL. "Edit.po" is an indicator to an HTML code reader of 
# what URL is DiscCatalog.html is mapped to.
#XMLC_Edit_OPTS = -urlmapping 'DiscCatalog.html?Edit.po' 'Edit.po'

XMLC_HTML_OPTS_FILE = options.xmlc

include $(ROOT)/config.mk
