
#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/presentation/assets/scripts

JAR_INSTALL =    ../../../resources/assets/scripts/*.js    

include $(ROOT)/config.mk




