#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/presentation/assets/images

JAR_INSTALL =    ../../../resources/assets/images/*.png  \
		../../../resources/assets/images/*.jpg

include $(ROOT)/config.mk
