#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..
protected static String FY_DEV_PAGE =   "/s_eventMgmt/fy_dev.po";
#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/presentation/s_eventMgmt

#
# To add new directories, create the directories and add their names
# this list. Be sure to copy a Makefile into each directory. Then add a
# "../" to the ROOT variable, and add the directory name to the end of.
# the PACKAGEDIR variable.
#

#
# To add more Java classes, create the .java files and add their names to
# this list (without the .java extension).
#
CLASSES = 		\
	SelectDate      \
	EditEvent        \
	ChangeEvent       \
	ShowEvent       \
	Selectdate_help   \
	Cancel_policy     \
	temp_event       \
	Show_conflicts   \
	Report_Gen	\
	Bill_report       \
	Annual_report	\
	FY_report	\
	Downtime            \
	Blocktime	\
	invoice \
	change	\
	recharge	\
	mainmenu	\
	Credit_report	\
	Debt_report   \
	BillingReports	\
	CancellationReports	\
	Event_Admin\
	fy_dev\
	annual_dev
	
HTML_DIR = ../../resources/s_eventMgmt

HTML_CLASSES = 		\
	SelectDateHTML	\
	EditEventHTML	\
	ChangeEventHTML    \
	ShowEventHTML    \
	changeHTML	\
	ChangeEventScriptHTML  \
	Selectdate_helpHTML   \
	Cancel_policyHTML	\
	Show_conflictsHTML      \
	Report_GenHTML		\
	Report_GenScriptHTML	\
	Bill_reportHTML		\
	DowntimeHTML		\
	BlocktimeHTML		\
	invoiceHTML		\
	rechargeHTML		\
	mainmenuHTML		\
	FY_reportHTML	\
	Annual_reportHTML	\
	Credit_reportHTML	\
	Debt_reportHTML  \
	BillingReportsHTML	\
	CancellationReportsHTML	\
	Event_AdminHTML\
	fy_devHTML\
	annual_devHTML
	

XMLC_HTML_OPTS_FILE = options.xmlc

include $(ROOT)/config.mk
