#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/presentation/media/js

JAR_INSTALL =    ../../../resources/media/js/*.js    

include $(ROOT)/config.mk



