      #
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#

PACKAGEDIR = webschedule/business/blocktime

CLASSES =			\
	Blocktimec			\
	BlocktimeFactory		

include $(ROOT)/config.mk

