#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#

PACKAGEDIR = webschedule/business/c_event

CLASSES =			\
	C_event			\
	C_eventFactory		

include $(ROOT)/config.mk

