#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
SUBDIRS = \
	css  \
	js

PACKAGEDIR = webschedule/presentation/media

JAR_INSTALL =    ../../resources/media/*.gif  \
		../../resources/media/*.css    \
		../../resources/media/*.jpg

include $(ROOT)/config.mk



