#
#  webschedule
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = webschedule/business

CLASSES =    webscheduleBusinessException
SUBDIRS = project person s_event downtime reporttrack operator operates r_event c_event complaint proposal

include $(ROOT)/config.mk

